teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 5  
    axis_linear:
      x: 1        
      y: 0        

    axis_angular:
      yaw: 3      

    scale_linear:
      x: 0.8     
      y: 0.4      
      z: 0.0
    
    scale_angular:
      yaw: 0.8    
      pitch: 0.0
      roll: 0.0
    
    scale_linear_turbo:
      x: 1.5
      y: 0.0
      z: 0.0